---
version: 3

images:
  base_image:
    name: docker.io/redhat/ubi10-minimal:10.2

options:
  package_manager_path: /usr/bin/microdnf

dependencies:
  system: files/bindep.txt
  ansible_core:
    # renovate: datasource=github-tags depName=ansible-runner packageName=ansible/ansible versioning=docker
    package_pip: ansible-core==2.21.2
  ansible_runner:
    # renovate: datasource=github-tags depName=ansible-runner packageName=ansible/ansible-runner versioning=docker
    package_pip: ansible-runner==2.4.3
  galaxy: files/requirements.yml
  python: files/requirements.txt
  python_interpreter:
      package_system: "python3.12"
      python_path: "/usr/bin/python3.12"
