---
version: 3

# requires redhat login
# images:
#   base_image:
#     name: registry.redhat.io/ansible-automation-platform-26/ee-minimal-rhel9:latest

images:
  base_image:
    name: redhat/ubi10-minimal:10.2

options:
  package_manager_path: /usr/bin/microdnf

additional_build_files:
  - src: files/ansible.cfg
    dest: configs

# additional_build_steps:
#   prepend_base:
#     - RUN dnf install -y python3.12 python3.12-pip python3.12-devel openssh-clients
#     - RUN python3 --version

dependencies:
  system: files/os-requirements.txt
  ansible_core:
    package_pip: ansible-core>=2.21.2
  ansible_runner:
    package_pip: ansible-runner
  galaxy: files/requirements.yml
  python: files/requirements.txt
  python_interpreter:
      package_system: "python3.12 python3.12-pip python3.12-devel"
      python_path: "/usr/bin/python3.12"
