---
  collections:
    - name: community.general
      source: https://galaxy.ansible.com
    - name: community.proxmox
      source: https://galaxy.ansible.com

# roles:
#   - name: initial_setup
#     src: https://github.com/ChrisZ-IT/initial_setup.git
#     version: v1.0.0